// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAClBY1GSsV8KYlEafeUu76GC03f6XA1wI',
    appId: '1:481724420176:web:0f69aee70bee2df9210155',
    messagingSenderId: '481724420176',
    projectId: 'jsolisting',
    authDomain: 'jsolisting.firebaseapp.com',
    storageBucket: 'jsolisting.appspot.com',
    measurementId: 'G-BZCTLYEXWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByogRLi35OpfjFnKutHzd_gay47fszsd4',
    appId: '1:481724420176:android:026cd3576a3c1104210155',
    messagingSenderId: '481724420176',
    projectId: 'jsolisting',
    storageBucket: 'jsolisting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAm2IKzsqCN5Sh_zdvNqsnjCzDecbJGs',
    appId: '1:481724420176:ios:03a258308b186a00210155',
    messagingSenderId: '481724420176',
    projectId: 'jsolisting',
    storageBucket: 'jsolisting.appspot.com',
    iosClientId: '481724420176-fv6rvsf73dcitvk9a13uu8tbr9dg3a68.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsoadminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfAm2IKzsqCN5Sh_zdvNqsnjCzDecbJGs',
    appId: '1:481724420176:ios:03a258308b186a00210155',
    messagingSenderId: '481724420176',
    projectId: 'jsolisting',
    storageBucket: 'jsolisting.appspot.com',
    iosClientId: '481724420176-fv6rvsf73dcitvk9a13uu8tbr9dg3a68.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsoadminpanel',
  );
}
